services:

  postgres:
    container_name: 'white-digital-postgres'
    image: postgres:latest
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    container_name: 'white-digital-redis'
    image: redis:latest
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - redis-data:/data/redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local